// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {clash} from '../models';
import {main} from '../models';
import {appcore} from '../models';
import {runtimeassets} from '../models';
import {sys} from '../models';
import {logger} from '../models';

export function AddRule(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AddRuleFromForm(arg1:string,arg2:string,arg3:clash.BuildRuleRequest):Promise<void>;

export function AddSubConverted(arg1:string,arg2:string,arg3:Record<string, string>):Promise<void>;

export function AddSubViaDNS(arg1:string,arg2:string):Promise<string>;

export function AddToGallery():Promise<Array<main.GalleryItem>>;

export function ApplyAppUpdate(arg1:string):Promise<void>;

export function ApplyGalleryToCard(arg1:string,arg2:string):Promise<string>;

export function CancelUpdateTask(arg1:string):Promise<void>;

export function CheckAndDownloadAppUpdateAsync():Promise<void>;

export function CheckCoreUpdateAsync():Promise<void>;

export function CheckTunEnv():Promise<Record<string, any>>;

export function ClearCardBg(arg1:string):Promise<void>;

export function ClearFinishedUpdateTasks():Promise<void>;

export function ClearLogs():Promise<void>;

export function ClearUpdateCache(arg1:string):Promise<void>;

export function CloseAllConnections():Promise<void>;

export function CloseConnection(arg1:string):Promise<void>;

export function DeleteConfig(arg1:string):Promise<void>;

export function DeleteFromGallery(arg1:string):Promise<Array<main.GalleryItem>>;

export function DeleteRule(arg1:string,arg2:string,arg3:number):Promise<void>;

export function DisableWarp():Promise<void>;

export function DoLocalImport(arg1:string,arg2:string):Promise<string>;

export function DownloadPendingAppUpdateAsync():Promise<void>;

export function EnableWarp():Promise<void>;

export function ExecuteRestore(arg1:string,arg2:string):Promise<string>;

export function ExportBackup():Promise<string>;

export function ExportConfig(arg1:string,arg2:boolean):Promise<void>;

export function ExportDiagnostics():Promise<void>;

export function FlushFakeIP():Promise<void>;

export function GetAppBehavior():Promise<appcore.AppBehavior>;

export function GetAppRouting(arg1:string):Promise<clash.AppRouting>;

export function GetAppState():Promise<appcore.AppState>;

export function GetAppVersion():Promise<string>;

export function GetCardBgs():Promise<Record<string, string>>;

export function GetCloseConnOnSwitch():Promise<boolean>;

export function GetComponentFileInfo():Promise<Record<string, runtimeassets.AssetHealth>>;

export function GetConfigFilePath(arg1:string):Promise<string>;

export function GetConnections():Promise<appcore.ConnectionsSnapshot>;

export function GetCoreVersion():Promise<string>;

export function GetCustomRules(arg1:string):Promise<Array<string>>;

export function GetDNSConfig():Promise<clash.DNSConfig>;

export function GetDataDirInfo():Promise<sys.DataDirInfo>;

export function GetDiagnosticInfo():Promise<appcore.DiagnosticInfo>;

export function GetEditableConfigs():Promise<Array<clash.ConfigTextResult>>;

export function GetGallery():Promise<Array<main.GalleryItem>>;

export function GetGpuSaver():Promise<boolean>;

export function GetHelperServiceStatus():Promise<sys.HelperStatusData>;

export function GetInitialData():Promise<Record<string, any>>;

export function GetLocalConfigs():Promise<Array<clash.SubIndexItem>>;

export function GetNetworkConfig():Promise<clash.NetworkConfig>;

export function GetOutboundIP(arg1:boolean):Promise<appcore.OutboundIPResult>;

export function GetOutboundIPForRoute(arg1:boolean,arg2:string):Promise<appcore.OutboundIPResult>;

export function GetProxyChains():Promise<Array<clash.ProxyChain>>;

export function GetProxyDelay(arg1:string,arg2:string):Promise<number>;

export function GetRecentLogs():Promise<Array<logger.LogEntry>>;

export function GetRouteConfig():Promise<clash.RouteConfig>;

export function GetRuleFormOptions(arg1:string):Promise<clash.RuleFormOptions>;

export function GetRulePageData(arg1:string):Promise<clash.RulePageData>;

export function GetRuntimeAssetStatus():Promise<runtimeassets.RuntimeAssetStatus>;

export function GetServiceCatalog():Promise<Array<clash.ServiceDef>>;

export function GetSmartRoute():Promise<boolean>;

export function GetStartupTaskInfo():Promise<sys.StartupTaskInfo>;

export function GetSubHeaders(arg1:string):Promise<Record<string, string>>;

export function GetTunConfig():Promise<clash.TunConfig>;

export function GetUwpApps():Promise<Array<sys.UwpApp>>;

export function GetWarpEnabled():Promise<boolean>;

export function GetWintunVersion():Promise<string>;

export function HideMainWindow():Promise<void>;

export function InstallHelperService():Promise<void>;

export function InstallSmartCore():Promise<void>;

export function InstallTunDriverAsync(arg1:boolean):Promise<void>;

export function IsConfigEditable(arg1:string):Promise<boolean>;

export function IsSmartCore():Promise<boolean>;

export function ListInstalledApps():Promise<Array<sys.AppInfo>>;

export function ProbeSubURL(arg1:string,arg2:Record<string, string>):Promise<clash.SubProbe>;

export function ReadConfigText(arg1:string):Promise<clash.ConfigTextResult>;

export function RemoveSmartCore():Promise<void>;

export function RemoveUpdateTask(arg1:string):Promise<void>;

export function RenameConfig(arg1:string,arg2:string):Promise<void>;

export function RepairCoreLayout():Promise<void>;

export function RepairDataDirMigration():Promise<void>;

export function RepairDataDirPermission():Promise<void>;

export function RepairRuntimeAssets():Promise<runtimeassets.RuntimeAssetStatus>;

export function RepairStartupTask():Promise<void>;

export function ResetComponentSettings(arg1:string):Promise<void>;

export function ResetTrafficTotals():Promise<void>;

export function RestartCore():Promise<void>;

export function RestartHelperService():Promise<void>;

export function SaveAppBehavior(arg1:appcore.AppBehavior):Promise<void>;

export function SaveCardToGallery(arg1:string):Promise<Array<main.GalleryItem>>;

export function SaveConfigText(arg1:string,arg2:string):Promise<void>;

export function SaveCustomRules(arg1:string,arg2:Array<string>):Promise<void>;

export function SaveDNSConfig(arg1:clash.DNSConfig):Promise<void>;

export function SaveNetworkConfig(arg1:clash.NetworkConfig):Promise<void>;

export function SaveProxyChains(arg1:Array<clash.ProxyChain>):Promise<void>;

export function SaveRouteConfig(arg1:clash.RouteConfig):Promise<void>;

export function SaveRuleSection(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function SaveSubHeaders(arg1:string,arg2:Record<string, string>):Promise<void>;

export function SaveThemePreference(arg1:boolean):Promise<void>;

export function SaveTunConfig(arg1:clash.TunConfig):Promise<void>;

export function SaveUwpExemptions(arg1:Array<string>):Promise<void>;

export function SearchLogs(arg1:string):Promise<Array<logger.LogEntry>>;

export function SelectAppExe():Promise<sys.AppInfo>;

export function SelectBackupFile():Promise<string>;

export function SelectLocalConfig(arg1:string):Promise<void>;

export function SelectLocalFile():Promise<main.FileInfo>;

export function SelectProxy(arg1:string,arg2:string):Promise<void>;

export function SetAppRouting(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function SetCardBg(arg1:string):Promise<string>;

export function SetCardBgData(arg1:string,arg2:string):Promise<string>;

export function SetCloseConnOnSwitch(arg1:boolean):Promise<void>;

export function SetGpuSaver(arg1:boolean):Promise<void>;

export function SetSmartRoute(arg1:boolean):Promise<void>;

export function ShowMainWindow():Promise<void>;

export function StartClash(arg1:string):Promise<void>;

export function StartConnectionMonitor():Promise<void>;

export function StartStreamingLogs():Promise<void>;

export function StopConnectionMonitor():Promise<void>;

export function SyncRules(arg1:string):Promise<void>;

export function SyncState():Promise<void>;

export function TestAllProxies(arg1:Array<string>):Promise<void>;

export function TestProxy(arg1:string):Promise<number>;

export function ToggleMainWindow():Promise<void>;

export function ToggleSystemProxy(arg1:boolean):Promise<void>;

export function ToggleTunMode(arg1:boolean):Promise<void>;

export function UninstallHelperService():Promise<void>;

export function UpdateAllGeoDatabasesAsync():Promise<void>;

export function UpdateAllSubsAsync():Promise<void>;

export function UpdateClashMode(arg1:string):Promise<void>;

export function UpdateCoreComponentAsync():Promise<void>;

export function UpdateGeoDatabaseAsync(arg1:string):Promise<void>;

export function UpdateSingleSub(arg1:string):Promise<void>;

export function UpdateSub(arg1:string,arg2:string):Promise<void>;

export function UpdateSubEx(arg1:string,arg2:string,arg3:Record<string, string>):Promise<void>;

export function ValidateConfigText(arg1:string):Promise<void>;

export function WorkshopDelete(arg1:number):Promise<string>;

export function WorkshopDownload(arg1:number):Promise<string>;

export function WorkshopEdit(arg1:number,arg2:string,arg3:string):Promise<string>;

export function WorkshopFetchImage(arg1:string):Promise<string>;

export function WorkshopGet(arg1:number):Promise<string>;

export function WorkshopLike(arg1:number):Promise<string>;

export function WorkshopList(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:number):Promise<string>;

export function WorkshopPublish(arg1:string,arg2:Array<string>):Promise<string>;

export function WorkshopReport(arg1:number,arg2:string):Promise<string>;
