// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRule(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddRule'](arg1, arg2, arg3);
}

export function AddRuleFromForm(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddRuleFromForm'](arg1, arg2, arg3);
}

export function ApplyAppUpdate(arg1) {
  return window['go']['main']['App']['ApplyAppUpdate'](arg1);
}

export function CancelUpdateTask(arg1) {
  return window['go']['main']['App']['CancelUpdateTask'](arg1);
}

export function CheckAndDownloadAppUpdateAsync() {
  return window['go']['main']['App']['CheckAndDownloadAppUpdateAsync']();
}

export function CheckCoreUpdateAsync() {
  return window['go']['main']['App']['CheckCoreUpdateAsync']();
}

export function CheckTunEnv() {
  return window['go']['main']['App']['CheckTunEnv']();
}

export function ClearFinishedUpdateTasks() {
  return window['go']['main']['App']['ClearFinishedUpdateTasks']();
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function ClearUpdateCache(arg1) {
  return window['go']['main']['App']['ClearUpdateCache'](arg1);
}

export function CloseAllConnections() {
  return window['go']['main']['App']['CloseAllConnections']();
}

export function CloseConnection(arg1) {
  return window['go']['main']['App']['CloseConnection'](arg1);
}

export function DeleteConfig(arg1) {
  return window['go']['main']['App']['DeleteConfig'](arg1);
}

export function DeleteRule(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteRule'](arg1, arg2, arg3);
}

export function DoLocalImport(arg1, arg2) {
  return window['go']['main']['App']['DoLocalImport'](arg1, arg2);
}

export function DownloadPendingAppUpdateAsync() {
  return window['go']['main']['App']['DownloadPendingAppUpdateAsync']();
}

export function ExecuteRestore(arg1, arg2) {
  return window['go']['main']['App']['ExecuteRestore'](arg1, arg2);
}

export function ExportBackup() {
  return window['go']['main']['App']['ExportBackup']();
}

export function ExportConfig(arg1, arg2) {
  return window['go']['main']['App']['ExportConfig'](arg1, arg2);
}

export function ExportDiagnostics() {
  return window['go']['main']['App']['ExportDiagnostics']();
}

export function FlushFakeIP() {
  return window['go']['main']['App']['FlushFakeIP']();
}

export function GetAppBehavior() {
  return window['go']['main']['App']['GetAppBehavior']();
}

export function GetAppState() {
  return window['go']['main']['App']['GetAppState']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetComponentFileInfo() {
  return window['go']['main']['App']['GetComponentFileInfo']();
}

export function GetConfigFilePath(arg1) {
  return window['go']['main']['App']['GetConfigFilePath'](arg1);
}

export function GetConnections() {
  return window['go']['main']['App']['GetConnections']();
}

export function GetCoreVersion() {
  return window['go']['main']['App']['GetCoreVersion']();
}

export function GetCustomRules(arg1) {
  return window['go']['main']['App']['GetCustomRules'](arg1);
}

export function GetDNSConfig() {
  return window['go']['main']['App']['GetDNSConfig']();
}

export function GetDataDirInfo() {
  return window['go']['main']['App']['GetDataDirInfo']();
}

export function GetDiagnosticInfo() {
  return window['go']['main']['App']['GetDiagnosticInfo']();
}

export function GetEditableConfigs() {
  return window['go']['main']['App']['GetEditableConfigs']();
}

export function GetHelperServiceStatus() {
  return window['go']['main']['App']['GetHelperServiceStatus']();
}

export function GetInitialData() {
  return window['go']['main']['App']['GetInitialData']();
}

export function GetLocalConfigs() {
  return window['go']['main']['App']['GetLocalConfigs']();
}

export function GetNetworkConfig() {
  return window['go']['main']['App']['GetNetworkConfig']();
}

export function GetOutboundIP(arg1) {
  return window['go']['main']['App']['GetOutboundIP'](arg1);
}

export function GetOutboundIPForRoute(arg1, arg2) {
  return window['go']['main']['App']['GetOutboundIPForRoute'](arg1, arg2);
}

export function GetProxyDelay(arg1, arg2) {
  return window['go']['main']['App']['GetProxyDelay'](arg1, arg2);
}

export function GetRecentLogs() {
  return window['go']['main']['App']['GetRecentLogs']();
}

export function GetRuleFormOptions(arg1) {
  return window['go']['main']['App']['GetRuleFormOptions'](arg1);
}

export function GetRulePageData(arg1) {
  return window['go']['main']['App']['GetRulePageData'](arg1);
}

export function GetRuntimeAssetStatus() {
  return window['go']['main']['App']['GetRuntimeAssetStatus']();
}

export function GetStartupTaskInfo() {
  return window['go']['main']['App']['GetStartupTaskInfo']();
}

export function GetTunConfig() {
  return window['go']['main']['App']['GetTunConfig']();
}

export function GetUwpApps() {
  return window['go']['main']['App']['GetUwpApps']();
}

export function GetWintunVersion() {
  return window['go']['main']['App']['GetWintunVersion']();
}

export function HideMainWindow() {
  return window['go']['main']['App']['HideMainWindow']();
}

export function InstallHelperService() {
  return window['go']['main']['App']['InstallHelperService']();
}

export function InstallTunDriverAsync(arg1) {
  return window['go']['main']['App']['InstallTunDriverAsync'](arg1);
}

export function IsConfigEditable(arg1) {
  return window['go']['main']['App']['IsConfigEditable'](arg1);
}

export function ReadConfigText(arg1) {
  return window['go']['main']['App']['ReadConfigText'](arg1);
}

export function RemoveUpdateTask(arg1) {
  return window['go']['main']['App']['RemoveUpdateTask'](arg1);
}

export function RenameConfig(arg1, arg2) {
  return window['go']['main']['App']['RenameConfig'](arg1, arg2);
}

export function RepairCoreLayout() {
  return window['go']['main']['App']['RepairCoreLayout']();
}

export function RepairDataDirMigration() {
  return window['go']['main']['App']['RepairDataDirMigration']();
}

export function RepairDataDirPermission() {
  return window['go']['main']['App']['RepairDataDirPermission']();
}

export function RepairRuntimeAssets() {
  return window['go']['main']['App']['RepairRuntimeAssets']();
}

export function RepairStartupTask() {
  return window['go']['main']['App']['RepairStartupTask']();
}

export function ResetComponentSettings(arg1) {
  return window['go']['main']['App']['ResetComponentSettings'](arg1);
}

export function ResetTrafficTotals() {
  return window['go']['main']['App']['ResetTrafficTotals']();
}

export function RestartCore() {
  return window['go']['main']['App']['RestartCore']();
}

export function RestartHelperService() {
  return window['go']['main']['App']['RestartHelperService']();
}

export function SaveAppBehavior(arg1) {
  return window['go']['main']['App']['SaveAppBehavior'](arg1);
}

export function SaveConfigText(arg1, arg2) {
  return window['go']['main']['App']['SaveConfigText'](arg1, arg2);
}

export function SaveCustomRules(arg1, arg2) {
  return window['go']['main']['App']['SaveCustomRules'](arg1, arg2);
}

export function SaveDNSConfig(arg1) {
  return window['go']['main']['App']['SaveDNSConfig'](arg1);
}

export function SaveNetworkConfig(arg1) {
  return window['go']['main']['App']['SaveNetworkConfig'](arg1);
}

export function SaveRuleSection(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveRuleSection'](arg1, arg2, arg3);
}

export function SaveThemePreference(arg1) {
  return window['go']['main']['App']['SaveThemePreference'](arg1);
}

export function SaveTunConfig(arg1) {
  return window['go']['main']['App']['SaveTunConfig'](arg1);
}

export function SaveUwpExemptions(arg1) {
  return window['go']['main']['App']['SaveUwpExemptions'](arg1);
}

export function SearchLogs(arg1) {
  return window['go']['main']['App']['SearchLogs'](arg1);
}

export function SelectBackupFile() {
  return window['go']['main']['App']['SelectBackupFile']();
}

export function SelectLocalConfig(arg1) {
  return window['go']['main']['App']['SelectLocalConfig'](arg1);
}

export function SelectLocalFile() {
  return window['go']['main']['App']['SelectLocalFile']();
}

export function SelectProxy(arg1, arg2) {
  return window['go']['main']['App']['SelectProxy'](arg1, arg2);
}

export function ShowMainWindow() {
  return window['go']['main']['App']['ShowMainWindow']();
}

export function StartClash(arg1) {
  return window['go']['main']['App']['StartClash'](arg1);
}

export function StartConnectionMonitor() {
  return window['go']['main']['App']['StartConnectionMonitor']();
}

export function StartStreamingLogs() {
  return window['go']['main']['App']['StartStreamingLogs']();
}

export function StopConnectionMonitor() {
  return window['go']['main']['App']['StopConnectionMonitor']();
}

export function SyncRules(arg1) {
  return window['go']['main']['App']['SyncRules'](arg1);
}

export function SyncState() {
  return window['go']['main']['App']['SyncState']();
}

export function TestAllProxies(arg1) {
  return window['go']['main']['App']['TestAllProxies'](arg1);
}

export function TestProxy(arg1) {
  return window['go']['main']['App']['TestProxy'](arg1);
}

export function ToggleMainWindow() {
  return window['go']['main']['App']['ToggleMainWindow']();
}

export function ToggleSystemProxy(arg1) {
  return window['go']['main']['App']['ToggleSystemProxy'](arg1);
}

export function ToggleTunMode(arg1) {
  return window['go']['main']['App']['ToggleTunMode'](arg1);
}

export function UninstallHelperService() {
  return window['go']['main']['App']['UninstallHelperService']();
}

export function UpdateAllGeoDatabasesAsync() {
  return window['go']['main']['App']['UpdateAllGeoDatabasesAsync']();
}

export function UpdateAllSubsAsync() {
  return window['go']['main']['App']['UpdateAllSubsAsync']();
}

export function UpdateClashMode(arg1) {
  return window['go']['main']['App']['UpdateClashMode'](arg1);
}

export function UpdateCoreComponentAsync() {
  return window['go']['main']['App']['UpdateCoreComponentAsync']();
}

export function UpdateGeoDatabaseAsync(arg1) {
  return window['go']['main']['App']['UpdateGeoDatabaseAsync'](arg1);
}

export function UpdateSingleSub(arg1) {
  return window['go']['main']['App']['UpdateSingleSub'](arg1);
}

export function UpdateSub(arg1, arg2) {
  return window['go']['main']['App']['UpdateSub'](arg1, arg2);
}

export function ValidateConfigText(arg1) {
  return window['go']['main']['App']['ValidateConfigText'](arg1);
}

export function ListInstalledApps() {
  return window['go']['main']['App']['ListInstalledApps']();
}

export function SelectAppExe() {
  return window['go']['main']['App']['SelectAppExe']();
}

export function GetAppRouting(arg1) {
  return window['go']['main']['App']['GetAppRouting'](arg1);
}

export function SetAppRouting(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetAppRouting'](arg1, arg2, arg3);
}

export function AddSubViaDNS(arg1, arg2) {
  return window['go']['main']['App']['AddSubViaDNS'](arg1, arg2);
}

export function IsSmartCore() {
  return window['go']['main']['App']['IsSmartCore']();
}

export function InstallSmartCore() {
  return window['go']['main']['App']['InstallSmartCore']();
}

export function RemoveSmartCore() {
  return window['go']['main']['App']['RemoveSmartCore']();
}

export function GetSmartRoute() {
  return window['go']['main']['App']['GetSmartRoute']();
}

export function SetSmartRoute(arg1) {
  return window['go']['main']['App']['SetSmartRoute'](arg1);
}

export function SetCardBg(arg1) {
  return window['go']['main']['App']['SetCardBg'](arg1);
}

export function GetCardBgs() {
  return window['go']['main']['App']['GetCardBgs']();
}

export function ClearCardBg(arg1) {
  return window['go']['main']['App']['ClearCardBg'](arg1);
}

export function GetGallery() {
  return window['go']['main']['App']['GetGallery']();
}

export function AddToGallery() {
  return window['go']['main']['App']['AddToGallery']();
}

export function SaveCardToGallery(arg1) {
  return window['go']['main']['App']['SaveCardToGallery'](arg1);
}

export function ApplyGalleryToCard(arg1, arg2) {
  return window['go']['main']['App']['ApplyGalleryToCard'](arg1, arg2);
}

export function DeleteFromGallery(arg1) {
  return window['go']['main']['App']['DeleteFromGallery'](arg1);
}

export function WorkshopList(arg1, arg2, arg3) {
  return window['go']['main']['App']['WorkshopList'](arg1, arg2, arg3);
}

export function WorkshopGet(arg1) {
  return window['go']['main']['App']['WorkshopGet'](arg1);
}

export function WorkshopDownload(arg1) {
  return window['go']['main']['App']['WorkshopDownload'](arg1);
}

export function WorkshopLike(arg1) {
  return window['go']['main']['App']['WorkshopLike'](arg1);
}

export function WorkshopReport(arg1, arg2) {
  return window['go']['main']['App']['WorkshopReport'](arg1, arg2);
}

export function WorkshopPublish(arg1, arg2) {
  return window['go']['main']['App']['WorkshopPublish'](arg1, arg2);
}

export function WorkshopFetchImage(arg1) {
  return window['go']['main']['App']['WorkshopFetchImage'](arg1);
}

export function SetCardBgData(arg1, arg2) {
  return window['go']['main']['App']['SetCardBgData'](arg1, arg2);
}

export function GetProxyChains() {
  return window['go']['main']['App']['GetProxyChains']();
}

export function SaveProxyChains(arg1) {
  return window['go']['main']['App']['SaveProxyChains'](arg1);
}
